version: "3"
services:
  postgres_db:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=skillsoft
    restart: unless-stopped
# APP*****************************************
  skillsoftapp:
    build: .
    network_mode: bridge
    container_name: skillsoftapp
    expose:
      - 5022
    ports:
      - 5022:5022
    restart: unless-stopped
    depends_on:
      - postgres_db
    links:
      - postgres_db
volumes:
  postgres-data: